---
name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check Terraform code is formatted
        uses: docker://hashicorp/terraform:latest
        with:
          entrypoint: terraform
          args: fmt -check -diff -recursive

  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Terraform init
        uses: docker://hashicorp/terraform:latest
        with:
          entrypoint: terraform
          args: init

      - name: Run Terraform validate
        uses: docker://hashicorp/terraform:latest
        with:
          entrypoint: terraform
          args: validate
